name: FNA-NET CI

on: [push, pull_request]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install workloads
      run: |
        dotnet workload install android ios tvos --skip-manifest-update

    - name: dotnet build and pack FNA-NET
      run: |
        dotnet build -c Debug FNA-NET.csproj
        dotnet pack FNA-NET.csproj

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build UWP
      run: msbuild FNA-NET.UWP.csproj -t:Restore,Pack /property:Configuration=Release

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }} Artifacts
        path: |
          bin/Release/*.nupkg
